export const PRICING_CONFIG = {
  starter: {
    name: "Starter",
    monthlyPrice: 1099,
    meetingFee: 50,
    sdrCapacity: "shared",
    sdrLabel: "Capacité SDR partagée",
    sdrShort: "SDR partagé",
    tagline: "Lancez votre première campagne outbound",
    positioning: "Idéal pour tester votre outbound",
    microcopy: "Testez le canal avant de scaler.",
    cta: "Commencer",
    highlight: false,
    features: [
      "Définition de l'ICP",
      "Recherche des entreprises cibles",
      "Recherche des décideurs",
      "Enrichissement des données",
      "Cold Email",
      "Prospection LinkedIn",
      "Séquences outbound",
      "Capacité SDR partagée",
      "Qualification des prospects",
      "Relances",
      "Prise de rendez-vous",
      "Reporting mensuel",
    ],
  },

  growth: {
    name: "Growth",
    monthlyPrice: 2099,
    meetingFee: 50,
    sdrCapacity: 1,
    sdrLabel: "1 SDR dédié à votre campagne",
    sdrShort: "1 SDR dédié",
    tagline: "Générez des rendez-vous régulièrement",
    positioning: "Notre offre la plus populaire",
    microcopy: "Une véritable capacité outbound intégrée à votre organisation.",
    cta: "Choisir Growth",
    highlight: true,
    features: [
      "Tout le contenu Starter",
      "1 SDR dédié à votre campagne",
      "Stratégie multicanale complète",
      "Cold Email",
      "LinkedIn Outreach",
      "Cold Calling",
      "Data enrichment avancé",
      "Personnalisation des campagnes",
      "Scripts de prospection",
      "Traitement des objections",
      "Qualification commerciale",
      "Booking des rendez-vous",
      "Optimisation continue",
      "Reporting hebdomadaire",
      "Dashboard de performance",
      "CRM setup & intégration",
    ],
  },

  scale: {
    name: "Scale",
    monthlyPrice: 4099,
    meetingFee: 50,
    sdrCapacity: 2,
    teamLead: true,
    sdrLabel: "2 SDR Senior + Team Lead",
    sdrShort: "2 SDR Senior",
    tagline: "Industrialisez votre acquisition",
    positioning: "Pour industrialiser votre outbound",
    microcopy: "Une équipe structurée pour industrialiser votre acquisition.",
    cta: "Passer à Scale",
    highlight: false,
    features: [
      "Tout le contenu Growth",
      "2 SDR Senior dédiés aux campagnes",
      "Supervision Team Lead",
      "Plusieurs ICP",
      "Plusieurs marchés",
      "Campagnes multicanales avancées",
      "Cold Email",
      "LinkedIn",
      "Cold Calling intensif",
      "Data enrichment avancé",
      "Account-Based Prospecting",
      "Automatisation avancée",
      "IA pour recherche, segmentation et personnalisation",
      "A/B Testing",
      "CRM Integration",
      "Reporting avancé",
      "Dashboard temps réel",
      "Suivi des opportunités",
      "Optimisation continue",
      "Playbooks sectoriels",
      "Support closing optionnel",
    ],
  },
} as const;

export const COMPARISON_TABLE = [
  { feature: "Prix mensuel", starter: "1 099 €", growth: "2 099 €", scale: "4 099 €" },
  { feature: "Performance", starter: "+50 €/RDV", growth: "+50 €/RDV", scale: "+50 €/RDV" },
  { feature: "SDR", starter: "Capacité partagée", growth: "1 SDR dédié", scale: "2 SDR Senior" },
  { feature: "Team Lead", starter: "—", growth: "Supervision", scale: "Inclus" },
  { feature: "ICP", starter: "1", growth: "1 principal", scale: "Plusieurs" },
  { feature: "Marchés", starter: "1", growth: "1 principal", scale: "Plusieurs" },
  { feature: "Data sourcing", starter: true, growth: true, scale: true },
  { feature: "Enrichissement", starter: "Standard", growth: "Avancé", scale: "Avancé" },
  { feature: "Cold Email", starter: true, growth: true, scale: true },
  { feature: "LinkedIn", starter: true, growth: true, scale: true },
  { feature: "Cold Calling", starter: "Relances / ciblé", growth: true, scale: "Intensif" },
  { feature: "Séquences", starter: true, growth: true, scale: "Avancées" },
  { feature: "Qualification", starter: true, growth: true, scale: true },
  { feature: "Meeting Booking", starter: true, growth: true, scale: true },
  { feature: "Personnalisation", starter: "Standard", growth: "Avancée", scale: "Avancée" },
  { feature: "Automation", starter: "Standard", growth: "Avancée", scale: "Avancée + IA" },
  { feature: "CRM Integration", starter: "Option", growth: true, scale: true },
  { feature: "Dashboard", starter: "Léger", growth: true, scale: "Temps réel" },
  { feature: "Reporting", starter: "Mensuel", growth: "Hebdomadaire", scale: "Avancé" },
  { feature: "A/B Testing", starter: "—", growth: "Limité", scale: true },
  { feature: "Account-Based Prospecting", starter: "—", growth: "—", scale: true },
  { feature: "Opportunity Tracking", starter: "—", growth: true, scale: true },
] as const;

export const PRICING_FAQ = [
  {
    question: "Y a-t-il un engagement ?",
    answer: "Nos engagements sont définis dans le contrat. Contactez-nous pour discuter des modalités adaptées à votre situation.",
  },
  {
    question: "Que signifie \"SDR dédié à votre campagne\" ?",
    answer: "Le SDR intervient directement sur vos campagnes : conversations, qualification et prise de rendez-vous. Il connaît votre offre, votre marché et vos personas pour maximiser la pertinence des échanges.",
  },
  {
    question: "Pourquoi une partie variable de 50 € par rendez-vous ?",
    answer: "Cette composante aligne une partie de notre rémunération avec la performance commerciale réellement produite. Vous payez pour les résultats concrets.",
  },
  {
    question: "Qu'est-ce qu'un rendez-vous qualifié tenu ?",
    answer: "Un rendez-vous est qualifié lorsqu'il correspond aux critères ICP convenus, implique un interlocuteur correspondant aux personas ciblés, a accepté le rendez-vous et participe effectivement à l'échange.",
  },
  {
    question: "Les outils sont-ils inclus ?",
    answer: "Oui, l'infrastructure technologique (enrichissement data, séquençage, automation) est incluse dans chaque offre. Aucun coût d'outil supplémentaire.",
  },
  {
    question: "Peut-on commencer avec Starter puis passer à Growth ?",
    answer: "Absolument. La montée en gamme est conçue pour accompagner votre croissance. Vous pouvez évoluer vers Growth ou Scale à tout moment.",
  },
  {
    question: "Puis-je ajouter un SDR supplémentaire ?",
    answer: "Oui, nous pouvons adapter la capacité SDR à vos besoins. Contactez-nous pour discuter d'une configuration sur mesure.",
  },
] as const;

export const QUALIFIED_MEETING_DEFINITION = {
  title: "Qu'est-ce qu'un rendez-vous qualifié tenu ?",
  criteria: [
    "Correspond aux critères ICP convenus",
    "Implique un interlocuteur correspondant aux personas ciblés ou validés",
    "A accepté le rendez-vous",
    "Participe effectivement à l'échange",
  ],
} as const;
